[project]
name = "ssm-tryout"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "einops>=0.8.1",
    "ipykernel>=7.1.0",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
